1.3.1

In [1]:
def create_chessboard():
    chessboard = []
    for i in range(8):
        row = []
        for j in range(8):
            row.append((i + j) % 2)
        chessboard.append(row)
    return chessboard
chessboard = create_chessboard()
for row in chessboard:
    print(row)

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


1.3.2

In [18]:
import numpy as np
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


1.3.3

In [3]:
import numpy as np
array = np.random.rand(3, 3, 3)
print(array)

[[[0.29394758 0.1185399  0.48118931]
  [0.15695049 0.42886561 0.81202758]
  [0.84720565 0.44535442 0.32064405]]

 [[0.26109532 0.20102721 0.01224605]
  [0.63150767 0.31686148 0.84636763]
  [0.92750631 0.93147867 0.5825584 ]]

 [[0.18445051 0.37643856 0.39682083]
  [0.14272939 0.39398489 0.69445084]
  [0.78505599 0.31647746 0.18507891]]]


1.3.4

In [21]:
import numpy as np
n = 6
matrix = np.zeros((n, n))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print(matrix)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


1.3.5

In [5]:
import numpy as np
array = np.random.randint(1, 100, size=10)
sorted_array = np.sort(array)[::-1]
print("Исходный массив:", array)
print("Отсортированный массив:", sorted_array)

Исходный массив: [37 47 22 56 84 46 53 40 28 29]
Отсортированный массив: [84 56 53 47 46 40 37 29 28 22]


1.3.6

In [22]:
import numpy as np
matrix = np.random.rand(5, 6)
print("Матрица:\n", matrix)
print("Форма:", matrix.shape)
print("Размер:", matrix.size)
print("Размерность:", matrix.ndim)

Матрица:
 [[0.45366799 0.34815941 0.10362572 0.98869745 0.02766635 0.46491697]
 [0.16969579 0.5876713  0.72825998 0.22680304 0.15640186 0.58920678]
 [0.00686912 0.17923065 0.98039862 0.89455019 0.34730979 0.94703616]
 [0.00590969 0.74393249 0.37998024 0.23253977 0.77647454 0.68010938]
 [0.86382953 0.1124139  0.55730206 0.77973271 0.69513867 0.46425372]]
Форма: (5, 6)
Размер: 30
Размерность: 2


2.3.1

In [23]:
import pandas as pd
import numpy as np
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])
distance = np.sqrt(np.sum((a - b) ** 2))
print("Евклидово расстояние:", distance)

Евклидово расстояние: 5.196152422706632


2.3.2

In [9]:
import pandas as pd

file_path = "data.csv"

# Чтение CSV-файла и создание фрейма данных
df = pd.read_csv(file_path)

# Вывод первых нескольких строк фрейма данных
print(df.head())

print()
print('-' * 80)
print()

# Вывод информации о фрейме данных
print(df.info())

print()
print('-' * 80)
print()


# Вывод статистического описания числовых столбцов
print(df.describe())

   stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer

--------------------------------------------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   stream      7 non-null      bool  
 1   slope       7 non-null      object
 2   elevation   7 non-null      object
 3   vegetation  7 non-null      object
dtypes: bool(1), object(3)
memory usage: 307.0+ bytes
None

--------------------------------------------------------------------------------

       stream  slope elevation vegetation
count       7      7         7          7
unique      2      3         4          3
top      True  steep      high  chapparal
freq        4      5 

2.3.3

In [12]:
import pandas as pd

file_path = "data.csv"

# Загрузка данных
df = pd.read_csv(file_path)

# 1. Базовый анализ данных
print("1. Общая информация о датасете:")
print(f"Количество записей: {len(df)}")
print(f"Количество столбцов: {len(df.columns)}")

print()
print('-' * 80)
print()

# 2. Анализ категориальных данных
print("\n2. Распределение по типам склона (slope):")
print(df['slope'].value_counts())

print()
print('-' * 80)
print()

print("\n3. Распределение по высоте (elevation):")
print(df['elevation'].value_counts())

print()
print('-' * 80)
print()

print("\n4. Распределение по типам растительности (vegetation):")
print(df['vegetation'].value_counts())

print()
print('-' * 80)
print()

# 3. Анализ наличия потоков
print("\n5. Статистика по наличию потоков (stream):")
print(df['stream'].value_counts())
print(f"Процент территорий с потоками: {(df['stream'].sum() / len(df)) * 100:.2f}%")

print()
print('-' * 80)
print()

# 4. Перекрестный анализ
print("\n6. Связь между высотой и типом растительности:")
print(pd.crosstab(df['elevation'], df['vegetation']))

print()
print('-' * 80)
print()

print("\n7. Связь между уклоном и наличием потока:")
print(pd.crosstab(df['slope'], df['stream']))

print()
print('-' * 80)
print()

# 5. Дополнительная информация о пропущенных значениях
print("\n8. Проверка на пропущенные значения:")
print(df.isnull().sum())

1. Общая информация о датасете:
Количество записей: 7
Количество столбцов: 4

--------------------------------------------------------------------------------


2. Распределение по типам склона (slope):
slope
steep       5
moderate    1
flat        1
Name: count, dtype: int64

--------------------------------------------------------------------------------


3. Распределение по высоте (elevation):
elevation
high       3
medium     2
low        1
highest    1
Name: count, dtype: int64

--------------------------------------------------------------------------------


4. Распределение по типам растительности (vegetation):
vegetation
chapparal    3
riparian     2
conifer      2
Name: count, dtype: int64

--------------------------------------------------------------------------------


5. Статистика по наличию потоков (stream):
stream
True     4
False    3
Name: count, dtype: int64
Процент территорий с потоками: 57.14%

---------------------------------------------------------------------

3.3.2

In [14]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Загрузка датасета Iris
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm', 'class']
df = pd.read_csv(url, header=None, names=column_names)

# Создание объектов для нормализации
min_max_scaler = MinMaxScaler()
standard_scaler = StandardScaler()

# Минимаксное преобразование для sepal_length_cm
df['sepal_length_normalized'] = min_max_scaler.fit_transform(df[['sepal_length_cm']])

# Z-масштабирование для sepal_width_cm
df['sepal_width_normalized'] = standard_scaler.fit_transform(df[['sepal_width_cm']])

# Вывод первых нескольких строк датасета для проверки
print(df[['sepal_length_cm', 'sepal_length_normalized', 'sepal_width_cm', 'sepal_width_normalized']].head())

# Вывод статистики нормализованных признаков
print("\nСтатистика нормализованных признаков:")
print(df[['sepal_length_normalized', 'sepal_width_normalized']].describe())


   sepal_length_cm  sepal_length_normalized  sepal_width_cm  \
0              5.1                 0.222222             3.5   
1              4.9                 0.166667             3.0   
2              4.7                 0.111111             3.2   
3              4.6                 0.083333             3.1   
4              5.0                 0.194444             3.6   

   sepal_width_normalized  
0                1.032057  
1               -0.124958  
2                0.337848  
3                0.106445  
4                1.263460  

Статистика нормализованных признаков:
       sepal_length_normalized  sepal_width_normalized
count               150.000000            1.500000e+02
mean                  0.428704           -6.631732e-16
std                   0.230018            1.003350e+00
min                   0.000000           -2.438987e+00
25%                   0.222222           -5.877635e-01
50%                   0.416667           -1.249576e-01
75%                   0.58333